name: Zack Design

description: Web applications, consulting, and project management

google_analytics: G-G929CKNR8F

url: https://zackdesign.biz
enforce_ssl: zackdesign.biz

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
