name: Zack Design
title: Zack Design
description: Software engineering, web development, and digital solutions by industry experts
tagline: Expert software engineering, consulting, and modern application development
author:
  name: Isaac Rowntree
  email: isaac@zackdesign.biz
  url: https://isaacrowntree.com

logo: /images/zackdesign-logo-symbol.png
image: /images/zackdesign-logo-symbol.png

google_analytics: G-G929CKNR8F

url: https://zackdesign.biz
enforce_ssl: zackdesign.biz
baseurl: ""
permalink: /:title/

# SEO Tag Settings
twitter:
  username:
  card: summary

social:
  name: Zack Design
  links:
    - https://github.com/zackdesign
    - https://github.com/isaacrowntree

# Locale settings
lang: en_US
locale: en_US

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - README.md
  - .git
